### ISSUE TITLE
issue with autoreconf

### ISSUE THREAD

**Issue by BouncyCCPP** [awslabs/certlint#1]
Hi,
We have download certlint and tried to build this module on RH Linux, Ruby 2.2.1.  We follow the instruction in 
build-x509helper/README.  At the autoreconf step, we ran into the following problem:

bash-3.2$ autoreconf -iv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
aclocal:configure.ac:13: warning: macro`AM_PROG_AR' not found in library
configure.ac:101: /usr/bin/m4: ERROR: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

If you have any suggestion to fix this problem, we will be grateful.
Thanks

**Comment by pzb** [comment]
What version of Red Hat Enterprise Linux are you using?

**Comment by BouncyCCPP** [comment]
Hi Peter,

I’m building it on Linux 2.6.18-308.11.1.el5.

Thanks

**Comment by guysagy** [comment]
The same thing happens on CentOS release 6.2 with Ruby version 2.2.4, gem version 2.4.8:

$ autoreconf -iv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
configure.ac:13: warning: macro`AM_PROG_AR' not found in library
/usr/bin/m4:configure.ac:101: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by guysagy** [comment]
After updating my operating system , the warning about the macro went away, but I am still getting the followup error due to the exceeded recursion limit:

$ autoreconf -iv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
/usr/bin/m4:configure.ac:99: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by guysagy** [comment]
Judging by posts in other threads, the issue was with our old gcc version / installation. 
Switching to using Linux Mint 17.1 with gcc version 4.8.4 solved the issues listed above.

**Comment by pzb** [comment]
I just updated the asn1c.patch and the asn1c project changed their configure.ac.

Can you remove the whole asn1c git checkout and try again?

**Comment by pzb** [comment]
It seems this issue is fixed.  If anyone else is experiencing the issue, please reopen.
