### ISSUE TITLE
Include more details on the RSA KU error

### ISSUE THREAD

**Issue by alex** [awslabs/certlint#10]
> `Unallowed key usage for RSA public key`

It'd be great if this said which key usage was disallowed, this is helpful in aggregating on different types of mistakes.

**Comment by selecadm** [comment]
Example: https://crt.sh/?id=12648791&opt=cablint

ERROR: Unallowed key usage for RSA public key

X509v3 Key Usage: critical
Digital Signature, Key Encipherment, Data Encipherment, Key Agreement

It's not obvious whether Data Encipherment, Key Agreement or both are disallowed.
