### ISSUE TITLE
CRLDP without HTTP

### ISSUE THREAD

**Issue by eabalea** [awslabs/certlint#18]
As per CABF BR, if the CRLDP extension is present, an HTTP URI MUST be present.
https://crt.sh/?id=5669744&opt=cablint shows that this isn't always the case, this should raise an error.

**Comment by pzb** [comment]
Fixed

**Comment by robstradling** [comment]
With https://github.com/awslabs/certlint/commit/2eca217a37b625cc05584b484625c820685c1823, _every_ certificate that contains the CRL Distribution Points extension is being flagged with "E: BR certificates with CRL Distribution Point must include HTTP URL".

ISTM that you either need to:
1. Prepend 2 SPACEs at the beginning of the 'URI:http://' string.
or
2. Add the following line immediately before the inner "unless":
          dps.each(&:lstrip!)
