### ISSUE TITLE
Don't treat known TLDs in UPPERCASE as unknown 

### ISSUE THREAD

**Issue by robstradling** [awslabs/certlint#2]
Example: https://crt.sh/?id=12118779&opt=cablint

**Comment by guidolotito** [comment]
Related to this: some certs are flagged with this error: "ERROR: commonNames in BR certificates must be from SAN entries" if the CN and SAN fail a case-sensitive comparison. But if the comparison was made in a case-insensitive manner, they would match. 

RFC 1034 says "By convention, domain names can be stored with arbitrary case, but domain name comparisons for all present domain functions are done in a case-insensitive manner"

**Comment by guidolotito** [comment]
An example of a cert flagged with "ERROR: commonNames in BR certificates must be from SAN entries" is https://crt.sh/test/?id=12130062.
