### ISSUE TITLE
Underscores in DNS names

### ISSUE THREAD

**Issue by robstradling** [awslabs/certlint#22]
https://crt.sh/?id=12815060&opt=cablint
"WARNING: Underscore should not appear in DNS names"

Would you consider removing that warning?
Or do we first need to get CABForum to vote on whether underscores should be permitted?

rsleevi finds it " 'not clear cut' as to what's expected".
https://www.mail-archive.com/dev-security-policy@lists.mozilla.org/msg02548.html

**Comment by pzb** [comment]
I'm not going to remove the warning.  It really should be an error but I'm going to leave it at a warning due to the ongoing discussion
