### ISSUE TITLE
Really add PKCS9String support

### ISSUE THREAD

**Issue by robstradling** [awslabs/certlint#26]
https://crt.sh/?id=12151484&opt=cablint
"FATAL: ASN.1 Error in PKCS9String"

https://github.com/awslabs/certlint/commit/80e0a8748c9a6bfdda502f45eef79e55e01a6e2c claimed to "Add PKCS9String support", but I don't see anything that relates to PKCS9String in the diff.

$ certlint-x509helper -p PKCS9String
-p PKCS9String: Unrecognized PDU
-p PKCS9String: Unrecognized option

**Comment by pzb** [comment]
Fixed in 712d8a0fcfcb21d3a74b96fba03cb58941060c2b
