### ISSUE TITLE
Count months correctly

### ISSUE THREAD

**Issue by robstradling** [awslabs/certlint#27]
https://crt.sh/?id=13469453&opt=cablint
"ERROR: BR certificates must be 39 months in validity or less"

This certificate is valid from the last day of month 1 (Feb 29th) until the penultimate day of month 39 (May 30th).  Therefore, its validity period does _not_ exceed 39 months.

This bit in cablint.rb seems to be the problem:
        if c.not_after.day > c.not_before.day
          months += 1
        end

I think it should consider the number of days left in the month after ".day" instead of the integer value of ".day".

**Comment by kroeckx** [comment]
I would argue that 1 month after February 29 would be March 29, not March 30 or March 31.

**Comment by kroeckx** [comment]
I guess you can also look at this the reverse way, and that 1 month before March 30 is February 29.

But I think the right way to look at it it to start from the start date and add the 39 months, and not try to subtract the 2 dates.

**Comment by robstradling** [comment]
Oracle's ADD_MONTHS function works like this:
https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions004.htm
"If date is the last day of the month or if the resulting month has fewer days than the day component of date, then the result is the last day of the resulting month. Otherwise, the result has the same day component as date."

Since the BRs don't currently mandate a particular method of counting months, I reckon that any popular method should be considered valid.

**Comment by pzb** [comment]
This should be fixed in 710234c22ddcad71be4d6e701cc66ed7638ea89c.  certlint now uses days rather than months and the number of days is calculated to be the maximum number that would ever make up _x_ months.
