### ISSUE TITLE
Why must CA certs have a Common Name?

### ISSUE THREAD

**Issue by guidolotito** [awslabs/certlint#28]
Peter, we see that certlint throws an error when this is violated: "CA certificates must include commonName in subject", but I can't find a reference for that. The closest I could find is 7.1.2.2.h, which says it must contain a country name and an org name.

At the last CABF F2F, Christy from Microsoft said that they'd like a CN in all Root certs as part of their policy, but she said nothing about Subordinate CAs.

**Comment by pzb** [comment]
This message has been moved to a notice and the wording clarified.
