### ISSUE TITLE
Subject Atrributes with no meaningful data

### ISSUE THREAD

**Issue by dougbeattie** [awslabs/certlint#29]
BR section 7.1.4.2.2 Subject DN Fields specifies the content for many fields, and you have checks for them in the tool already.  Item i. says that "Optional attributes MUST NOT contain metadata such as ‘.’, ‘-‘, and ‘ ‘ (i.e. space) characters, and/or any other indication that the value is absent, incomplete, or not applicable."  I take this to mean fields that contain only characers like those listed above.

Should it be a BR error or warning if a field such as the OU contains ONLY ‘.’, ‘-‘, and/or ‘ ‘ ?  Maybe this applies to any field in the subject DN?

**Comment by pzb** [comment]
So I'm thinking that any sane attribute should match `/\p{L}|\p{N}/`, which means at least one letter or number in any language.  If it is only punctuation or non-printable characters, then it is highly unlikely to be valid.
