### ISSUE TITLE
Filter for Certificates only (no precertificates)

### ISSUE THREAD

**Issue by dougbeattie** [awslabs/certlint#32]
It would be useful to view a list of certificates only (no precertificates).  Today I can get a list of 
- TLS Server certificate identified - which includes precertificates and certificates
- EV certificate identified - which included EV precertifciates and EV certificates
- Certificate Transparency Precertificate identified - which filters out certificates
  but, I can't get a list of just certificates (those that are "TLS Server certificate identified" minus "Certificate Transparency Precertificate identified"

Is that something worth adding?

**Comment by pzb** [comment]
I think you are referring to crt.sh which is over at https://github.com/crtsh/certwatch_db.  Alternatively contact @robstradling, the maintainer of crt.sh.

**Comment by robstradling** [comment]
crt.sh uses cablint's categorizations though.  e.g., https://crt.sh/?cablint=7&iCAID=1151 shows TLS Server Certificates recently issued by a particular GlobalSign intermediate.

cablint doesn't currently output "I: Certificate identified" whenever the cert is not a precertificate.  If you could add that, that would enable crt.sh to provide Doug with what he's looking for.
