### ISSUE TITLE
CN and SAN should be compared in case-insensitive manner

### ISSUE THREAD

**Issue by guidolotito** [awslabs/certlint#8]
https://crt.sh/?id=12188061&opt=cablint shows this error:
ERROR: commonNames in BR certificates must be from SAN entries

I think it's because the TLD in the CN has an uppercase Q, but in the SAN it has a lowercase Q.

As with other issues, domain names are supposed to be compared in a case-insensitive manner

**Comment by pzb** [comment]
The error is because certlint currently doesn't treat u-labels as equal to a-labels.  This is the same issue as #3
